ADMIN CONTROL PANEL
The theme has been updated.
×
Edison Leon(Sign Out)
Back To Site
Wine Spectator Forums
WINE SPECTATOR FORUMSADMIN CONTROL PANELTHEMESEDIT THEME
Design
Basics Member Management Content Management1 Design Web Space Reports Module Settings Groups Recipes Advanced Settings FeePod Plan/Billing
DISPLAY SETTINGS
STANDARD THEMES
NEWS FLASH
CUSTOM PAGES
WORDLETS
GRAEMLINS
CUSTOM/EMBEDDED WIDGETS
EMAIL THEME
Edit Theme
Theme Name
Wine Spectator Theme
Expand All · Collapse All
Custom CSS/HEAD Code
Custom Code For HEAD Section OPTIONAL
This code will be inserted inside the HTML HEAD tags for all pages using this theme.
Custom CSS OPTIONAL
Apply any custom CSS. You should not wrap this CSS with a STYLE tag. This CSS will be applied to all pages that use this theme, and it will take precedence over your global HEAD and CSS.
Fonts
Font Family
Base Font Size:	16px
Page Background
Apply Background Color:	#FFFFFF	Opacity: 1.00
Apply Background Image
Top Nav Bar
Background Color:	#666666
Font Color:	#FFFFFF
Icon Color:	#FFFFFF
Highlighted Item Background Color:	#8D0004
Highlighted Item Font Color:	#FFFFFF
Submenu Border Color:	#666666
Make Fixed:	Yes
Contain To Content Width:	No
Off Canvas Nav Bar
The "Off Canvas" nav bar is a slide out menu that is only displayed on smaller screens when a user clicks on the menu icon that appears on the left or right side.

Background Color:	#333333	Opacity: 1.00
Font Color:	#B8B8B8
Alert Box Background Color:	#8D0004	Opacity: 1.00
Alert Box Font Color:	#FFFFFF
Highlighted Item Background Color:	#8D0004	Opacity: 1.00
Highlighted Item Font Color:	#FFFFFF
Side Nav
The Side Nav (.side-nav) is used on Member Settings pages and on QuestionShark topic lists.

Background Color:	#F8F8F8	Opacity: 1.00
Font/Link Color:	#8D0004
Outer Box Border Color:	#DFDFDF
Default Content
The is the standard presentation for all content.

Background Color:	#E0DED7	Opacity: 1.00
Border Color:	#DFDFDF
Font Color:	#333333
Secondary Font Color:	#DFDFDF
Link Color:	#1865AD
Validation Font Color:	#F04124
Site Header
This is the area at the top of your pages, typically directly below (or above) your main navigation menu.

Inherit Default Content Background and Font Colors
Form Elements
These colors are used to style form elements like inputs, textareas and select dropdowns.

Background Color
#FFFFFF
Opacity: 1.00
Border Color
#CCCCCC
Font Color
#333333
Placeholder Color
#CCCCCC
Cards
Cards are typically used to display lists of content.

Background Color
#FFFFFF
Opacity: 1.00
Border Color
#DFDFDF
Font Color
#C6C6C6
Link Color
#008CBA
Featured Content Link Color
#E85B51
Avatar Border Color
#333333
Bottom Bar Background Color
#F0F0F0
Opacity: 1.00
Bottom Bar Font Color
#333333
Private Content Background Color
#FFFEFA
Opacity: 1.00
Post Boxes
Post boxes (.post-box) are used for topics, private messages, comment/reply posts, and user notes.

Background Color
#E0DED7
Opacity: 1.00
Item Border Color
#DFDFDF
Font Color
#333333
Secondary Font Color
#DFDFDF
Link Color
#1865AD
Featured Content Link Color / Activity Border Color
#E85B51
Private Content Background Color
#FFFEFA
Opacity: 1.00
Module Color
These colors are used on the top border of content cards, as well as other areas to differentiate content types. Choose colors that will complement each other.

Forum Color
#C5D83F
Blog Color
#F2794F
Survey Color
#F5CB07
Clips Color
#EA80FC
Chat Color
#FC80D1
Calendar Color
#C8AA4C
QuestionShark Color
#ECC407
Database Color
#0EBFD2
Private Messages Color
#B31837
Action Boxes
Action boxes (.action-box) are shaded action links that typically appear at the top of the right column for many pages.

Background Color
#F8F8F8
Opacity: 1.00
Box Outside Border Color
#DFDFDF
Inherit Default Content Font and Link Colors
Breadcrumbs
Breadcrumbs (.breadcrumbs) is a shaded section that appears on every page and gives context of where the page lives on the site. By default, Action Box styling will be used. You can override those settings by unchecking the box below, however.

Inherit Action Boxes Settings
Callout Boxes
Callout boxes (.callout-box) are used for content that needs special emphasis.

Background Color
#F8F8FD
Opacity: 1.00
Box Outside Border Color
#DFDFDF
Inherit Default Content Font and Link Colors
Section Boxes
Regular section boxes (.section-box) have titles that are shaded, while alternate section boxes (.alt-section-box) have shading on the section bodies instead. The non shaded areas use the Default Content settings.

Shaded Area Background Color
#F8F8F8
Opacity: 1.00
Shaded Area Outer Border Color
#DFDFDF
Inherit Default Content Font and Link Colors
List Boxes
List boxes (.list-box) are shaded rows of data. By default, Section Box styling will be used. You can override those settings by unchecking the box below, however.

Inherit Section Boxes Settings
Widgets
Widgets are displayed in the right sidebar on many pages.

Background Color
#F8F8F8
Opacity: 1.00
Box Outside Border Color
#DFDFDF
Inherit Default Content Font and Link Colors
Dropdowns
Dropdown menus (.f-dropdown) are sub-menus displayed in places such as the Search box dropdown in the Top Nav Bar, Off Canvas Menu submenus, and on some Buttons.

Background Color
#FFFFFF
Opacity: 1.00
Border Color
#DFDFDF
Inherit Default Content Font and Link Colors
Tooltips
A Tooltip is explanatory text that is displayed on hover of text. These settings control the display of the tooltip overlay.

Background Color
#222222
Opacity: 1.00
Font Color
#FFFFFF
Icons
We use font icons, so you can adjust the colors of all icons here.

Default Icon Color
#929292
Online/Selected State Color
#268024
In Button - Standard Color
#FFFFFF
In Button - 'On' State Color
#FEF9B3
Component Colors
We use Foundation's stock colors for buttons, labels, and alert boxes. Check the box below to override and set your own colors for Primary, Secondary (.secondary), Info (.info), Success (.success), Warning (.warning), and Alert (.alert). The system will automatically create a proper hover color for your custom background colors. The Catch-All color is used for labels with these classes: .category, .set, .calendar, .completed.

Override Stock Component Colors
Media Player
You can customize the appearance of the audio, video, and image slideshow players.

Middle Bar Background Color
#232323
Middle Bar Font Color
#FFFFFF
Button Component Color
Miscellaneous
Survey Bar Graph Color
#E3BD27
Need Help?
Feeling stuck or just not sure how to do something? We've got your back. Pop into our support community anytime!

Already asked a question and wondering where to find it? Check your list of support topics.

