.h-ubb-topic-list-box .member-avatar { display:none; } 
footer.site-footer h3{font-size:20px; color:#fff; line-height: 1.4; margin-bottom: 16px} 
footer.site-footer li, nav.site-navigation li{font-size:16px;line-height:1.35; margin-bottom:8px;}
nav.site-navigation a{font-size:14px;}
footer.site-footer ul{margin-bottom:48px;} 
footer.site-footer  a:hover, nav.site-navigation a:hover{color:#fff;} 
nav.site-navigation{margin-bottom:0;}
nav.site-navigation li{margin-bottom:0;} 
header .button.button--subscribe{background: #fff; font-weight: 700; border-radius: .25em; padding: 9px 13px; font-size:13px; line-height:1.35;} 
header .button.button--subscribe:hover{color: #161616;}
header.site-header{position: relative;} 
.site-navigation.background-alpha ul li a{color:#fff !important;} .site-navigation.background-alpha ul li a:visited{color:#fff !important;} 
.post-box-meta, .post-box-meta .fa-any, .post-box-meta a, .post-box-meta a:hover {
    color: #1865AD;
} 