<header class="site-header background-alpha">
    <div class="site-header__layout">

        <div class="site-header__hamburger"></div>

        <a class="u-display-block" href="https://www.winespectator.com" data-gaevent="true" data-gaeventlabel="logo-icon" data-gaeventlocation="top-navbar" title="Wine Spectator">
            <img class="site-header__logo" src="https://s3.amazonaws.com/assets.mshanken.com/sys/ws/css/img/wslogo.png" alt="Wine Spectator" />
        </a>

        <div class="site-header__controls">
            <a target="_blank" data-gaevent="true" data-gaeventlabel="top-navbar" data-gaeventlocation="subscribe" href="https://onlinesub.winespectator.com/pubs/M5/WSO/2weektrial2017.jsp?cds_page_id=155136&cds_mag_code=WSO&id=1555085022334&lsid=91021037288023932&vid=4" class="button button--subscribe" title="Subscribe to Wine Spectator">Subscribe</a>

            <a href="/search" data-gaevent="true" data-gaeventlabel="search-icon" data-gaeventlocation="top-navbar" title="Search" class="search-icon__link"></a>

            <div class="dropdown-container" aria-haspopup="true"></div>
        </div>
    </div><!-- /.site-header__layout -->
</header>

<nav class="site-navigation background-alpha">
    <ul>
        <li><a href="https://www.winespectator.com/ratings" data-gaevent="true" data-gaeventlabel="ratings" data-gaeventlocation="main-navbar">Ratings</a></li>
        <li><a href="https://www.winespectator.com/wine-iq" data-gaevent="true" data-gaeventlabel="wine-iq" data-gaeventlocation="main-navbar">Wine IQ</a></li>
        <li><a href="https://www.winespectator.com/news" data-gaevent="true" data-gaeventlabel="news" data-gaeventlocation="main-navbar">News</a></li>
        <li><a href="/wine-and-culture" data-gaevent="true" data-gaeventlabel="wine-and-culture" data-gaeventlocation="main-navbar">Wine &amp; Culture </a></li>
        <li><a href="//restaurants.winespectator.com/" >Restaurants</a></li>
        <li><a href="https://www.winespectator.com/food" data-gaevent="true" data-gaeventlabel="food" data-gaeventlocation="main-navbar">Food</a></li>
        <li><a href="https://www.winespectator.com/video" data-gaevent="true" data-gaeventlabel="video" data-gaeventlocation="main-navbar">Video</a></li>
    </ul>
</nav>
<div style="text-align: center; border-top: 1px solid #ccc; border-bottom: 1px solid #ccc; margin-bottom: 32px; background:#f3f3f3;">
    <div class="">
		<div class="iab-adcontent ad-strip">
			<div id="billboard_192" style="margin: 0 auto; padding: 0; text-align: center;">
				<script>
        googletag.cmd.push(function() {
          googletag.display('billboard_192');
        });
      </script>
			</div>
		</div>
 	</div>
</div>