<!-- Start: Instsert HEAD Tags -->
	<meta name="keywords" content="Wine Spectator, Wine Spectator Online,winespectator, wine, magazine, rating, score, review, tasting, note, report,price, red, white, cabernet, sauvignon, merlot, syrah, shiraz, pinot, noir, grigio, chardonnay, champagne, news, information, forum, food, dining,restaurant, travel, resort, hotel, basic, vintage, chart, collecting,auction, storage, winery, wineries, retailer, calendar, event, classified,job, gift, accessory, accessories, back issue, search, Wine Experience, Grand Tour, Restaurant Award, Wine Spectator Weekly, Wine of the Week, Wine of the Day, Smart Buys, Top 100, subscription, account, customer service,advertising">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<!-- Begin UA code --><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  // Adding attempt at basic sub tracking on 4/13/2017 VanHook
  memberType = 'ANON';
  allCookies = document.cookie;
  if(allCookies) {
    wsoCookie = document.cookie.indexOf('wso_session');
    console.log('wso_session: ',wsoCookie);

    if(wsoCookie > -1)
      memberType = 'SUB'
  }

  ga('create', 'UA-23484466-20', 'winespectator.com');
  ga('require', 'linkid', 'linkid.js');
  ga('set', {"hitType":"pageview","dimension1":"forums","dimension2":memberType,"dimension3":"forums"});

</script>
<!-- End UA code -->
<script type='text/javascript'>
		var googletag = googletag || {};
		googletag.cmd = googletag.cmd || [];
		(function() {
			var gads = document.createElement('script');
			gads.async = true;
			gads.type = 'text/javascript';
			var useSSL = 'https:' == document.location.protocol;
			gads.src = (useSSL ? 'https:' : 'http:') + '//www.googletagservices.com/tag/js/gpt.js';
			var node = document.getElementsByTagName('script')[0];
			node.parentNode.insertBefore(gads, node);
		})();
	</script>
<!-- Google For DFP -->
    <script type='text/javascript'>
    var googletag = googletag || {};
    googletag.cmd = googletag.cmd || [];
    (function() {
        var gads = document.createElement('script');
        gads.async = true;
        gads.type = 'text/javascript';
        var useSSL = 'https:' == document.location.protocol;
        gads.src = (useSSL ? 'https:' : 'http:') + '//www.googletagservices.com/tag/js/gpt.js';
        var node = document.getElementsByTagName('script')[0];
        node.parentNode.insertBefore(gads, node);
    })();
</script>
<script>
    window.googletag = window.googletag || {cmd: []};
	googletag.cmd.push(function() {
		var mapping = googletag.sizeMapping().
	  		addSize([1024,0], [[970,250], [728,90]]).
	  		addSize([748,0], [[728,90]]).
	  		addSize([300,0], [[300,50],[300, 40]]).
	  		build();
    	googletag.
	        defineSlot('/4054/NEW.WS.General', [[970,250],[728,90],[300,250]], 'billboard_192').
	        addService(googletag.pubads()).
	        defineSizeMapping(mapping).
	        setTargeting("pos", 'billboard_1').
	        setTargeting("tile", '1').
	        setTargeting("rb", 'y');
    	googletag.enableServices();
    });
    googletag.cmd.push(function() {
		var mapping = googletag.sizeMapping().
	  		addSize([1024,0], [[300, 600]]).
	  		addSize([748,0], [[300,250]]).
	  		addSize([300,0], [[300,50], [300,40]]).
	  		build();
    	googletag.
	        defineSlot('/4054/NEW.WS.General', [[300,600], [300,250], [300,50], [300,40], [10,10], [1,1]], 'rectangle_184').
	        addService(googletag.pubads()).
	        defineSizeMapping(mapping).
	        setTargeting("pos", 'sidebox_1').
	        setTargeting("tile", '8').
	        setTargeting("rb", 'y');
    	googletag.enableServices();
    });
    googletag.cmd.push(function() {
		googletag.
	        defineSlot('/4054/NEW.WS.General', [[300,250], [10,10]], 'div-gpt-ad-slot').
	        addService(googletag.pubads()).
	        setTargeting("pos", 'sidebox_2').
	        setTargeting("tile", '9').
	        setTargeting("rb", 'y');
    	googletag.enableServices();
    });
</script>
    <!-- End: Google For DFP -->
<link rel="stylesheet" type="text/css" href="//s3.amazonaws.com/assets.mshanken.com/css/wso-forums.css" />